Package bundling and new barcode types were added
EddieLa/JOB pull request #60
Opened 2018-06-04 11:34 UTC by ilguzin

- Webpack has been engaged into the distribution process. Updated the sample layout code.
- Added support for "Code11" and "CodeMSI"

2018-10-26 15:10 UTC, seangates requested changes
Fix these, and I'll see if I can get @EddieLa to merge this PR.

2018-10-26 15:10 UTC, seangates commented on src/DecoderWorker.js
> +      //}
Remove comments if not used.

2018-10-26 15:10 UTC, seangates commented on src/DecoderWorker.js
> +        }
Remove unused code.

2018-10-26 15:10 UTC, seangates commented on src/DecoderWorker.js
> +    // console.log("CheckCodeMSI", string);
Remove unnecessary code.

2018-10-26 15:10 UTC, seangates commented on src/DecoderWorker.js
> +    //}
Remove unused code.

2018-10-26 15:10 UTC, seangates commented on src/DecoderWorker.js
> +          // binaryString.splice(0, 1)[0]; // todo uncomment?
Remove unused code.

2019-10-08 07:57 UTC, ilguzin commented
Sorry for not giving a feedback on this for so long. Accidentally found it to be still open :-)

2021-10-08 05:48 UTC, closed without merging